### ISSUE TITLE
No result/logger information

### ISSUE THREAD

**Issue by lockwo** [entropicalabs/openqaoa#111]
The documentation for the logger and results is empty (https://el-openqaoa.readthedocs.io/en/latest/logger_and_results.html). I'm not sure if it doesn't exist or isn't being generated properly, but it is valuable documentation to have available. 
![image](https://user-images.githubusercontent.com/42878312/198162636-ecd15426-0f93-42bc-9350-66501a645fa8.png)

**Comment by Q-lds** [comment]
Well spotted! This is indeed a bug! Actually, there was an issue with the doc-building test (it turns out that sphinx-build needs the flag `-W` in order to return `1` and signal that to the user) ... so we were fooled by tests always being green! 

I have started fixing this and issue #106 too. 

Regarding the status of the underlying docstrings: the result one should be fairly complete, while the logger one requires some improvements.

**Comment by vishal-ph** [comment]
Closing this issue, the docs were fixed in PR113
